#!/usr/bin/env bash

echo -n "User: "
read HTTP_CNTRL_USER

echo -n "Password: "
read -s HTTP_CNTRL_PASSWORD
echo -e "\n"

KEY=$(python -c "import base64,hashlib;print(hashlib.sha1(base64.b64encode('$HTTP_CNTRL_USER:$HTTP_CNTRL_PASSWORD')).hexdigest())")
echo "Test it: curl -i -u \"$HTTP_CNTRL_USER:$HTTP_CNTRL_PASSWORD\" localhost:8080/ps"
set -x
python -u http_cntrl.py -r ./scripts/commands -p 8080 --route=test1:scripts/hs2_test --route=restart:restart --route=ps:ps -k $KEY
set +x